apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres-service:5432/chatbot
  SECRET_KEY: "8f277e63178e6e98df07661b6cdbd032db9c2a4f12ef5c0be27ba161c6008583"
  LLM_API_KEY: "sk-d1821e9c23c1c3c8c642b3e87ca5f533f9623280bb54814f22357960fdde334e"
  LLM_BASE_URL: "https://api.xah.io/v1"
  LLM_MODEL: "deepseek-v4-flash"
